"""
Django settings for univesp_tcc project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import secrets
from urllib.parse import urlparse

from pathlib import Path

import dj_database_url
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", default=secrets.token_urlsafe(nbytes=64)
)

# A variável de ambiente `DYNO` está definida na Heroku CI, mas não é um aplicativo Heroku real,
# então também temos que excluir explicitamente o CI:
# https://devcenter.heroku.com/articles/heroku-ci#immutable-environment-variables
IS_HEROKU_APP = "DYNO" in os.environ and not "CI" in os.environ

# SECURITY WARNING: don't run with debug turned on in production!
if not IS_HEROKU_APP:
    DEBUG = True

# Na Heroku, é seguro usar um curinga para `ALLOWED_HOSTS`, pois o roteador Heroku realiza
# a validação do cabeçalho Host na solicitação HTTP recebida. Em outras plataformas,
# você pode precisar listar explicitamente os nomes de host esperados para evitar ataques
# de cabeçalho de host HTTP. Veja:
# https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-ALLOWED_HOSTS
if IS_HEROKU_APP:
    ALLOWED_HOSTS = ["*"]
    SECURE_SSL_REDIRECT = False
else:
    ALLOWED_HOSTS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    # Use a implementação runserver do WhiteNoise em vez do padrão do Django, para paridade dev-prod.
    'whitenoise.runserver_nostatic',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'seniorguard',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Adicionado pacote WhiteNoise para servir ativos estáticos
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'univesp_tcc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'univesp_tcc.wsgi.application'
ASGI_APPLICATION = "univesp_tcc.asgi.application"


def build_channel_layers(redis_url_value):
    if not redis_url_value:
        return {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer",
            },
        }

    redis_url = urlparse(redis_url_value)
    default_port = 6380 if redis_url.scheme == "rediss" else 6379
    hostname = redis_url.hostname or "localhost"
    port = redis_url.port or default_port
    host_config = {
        "address": f"{redis_url.scheme}://{hostname}:{port}{redis_url.path or ''}",
    }
    if redis_url.username is not None:
        host_config["username"] = redis_url.username
    if redis_url.password is not None:
        host_config["password"] = redis_url.password

    return {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [host_config],
            },
        },
    }


REDIS_URL = os.environ.get("REDIS_URL")
CHANNEL_LAYERS = build_channel_layers(REDIS_URL)


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
if IS_HEROKU_APP:
    # Na produção na Heroku, a configuração do banco de dados é derivada da variável de ambiente
    # `DATABASE_URL` pelo pacote dj-database-url. `DATABASE_URL` será definido automaticamente
    # pela Heroku quando um complemento de banco de dados for anexado ao seu aplicativo Heroku. Veja:
    # https://devcenter.heroku.com/articles/provisioning-heroku-postgres
    # https://github.com/jazzband/dj-database-url
    database_url = os.environ.get("PGBOUNCER_URL") or os.environ.get("DATABASE_URL")
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=0,
            conn_health_checks=True,
            ssl_require=True,
        ),
    }
else:
    # Ao executar localmente em desenvolvimento ou em CI, um arquivo de banco de dados sqlite
    # será usado para simplificar a configuração inicial. A longo prazo, é recomendado usar o
    # Postgres localmente também.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = 'static/'

# Não armazene a versão original (nome de arquivo sem hash) de arquivos estáticos, para reduzir o tamanho do slug:
# https://whitenoise.readthedocs.io/en/latest/django.html#WHITENOISE_KEEP_ONLY_HASHED_FILES

WHITENOISE_KEEP_ONLY_HASHED_FILES = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Heroku settings
django_heroku.settings(locals(), staticfiles=False)
