# Generated by Django 5.1.1 on 2025-09-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Novo Dispositivo', max_length=32),
        ),
    ]
