# Generated by Django 5.1.1 on 2025-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorguard', '0002_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Novo Dispositivo IoT', max_length=32),
        ),
    ]
