# Generated by Django 5.1.1 on 2025-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorguard', '0003_alter_device_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensortype',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='sensortype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
